development:
  adapter: postgresql
  database: box
  pool: 5
  timeout: 5000
  username: <%= ENV['BOX_PG_USERNAME'] %>
  password: <%= ENV['BOX_PG_PASSWORD'] %>

test:
  adapter: postgresql
  database: box_test
  timeout: 5000
  username: <%= ENV['BOX_PG_USERNAME'] %>
  password: <%= ENV['BOX_PG_PASSWORD'] %>

production:
  adapter: postgresql
  database: box
  pool: 5
  timeout: 5000
  username: <%= ENV['BOX_PG_USERNAME'] %>
  password: <%= ENV['BOX_PG_PASSWORD'] %>